language: cpp

compiler: clang

sudo: required

addons:
  apt:
    sources:
      - 'ppa:h-rayflood/llvm'
    packages:
      - clang-3.6

install:
  - true

script:
  - true

notifications:
  email: false
