language: ruby
cache: bundler
sudo: false

env:
  matrix:
    # The first one is intentionally empty in order to run without any extra env vars
    -
    - SKYLIGHT_DISABLE_AGENT=true

rvm:
  - 2.3.0
matrix:
  allow_failures:
    # Testing edge is nice, but it probably shouldn't kill the build
    - gemfile: gemfiles/Gemfile.sinatra-edge

install:
  - true

script:
  - true

notifications:
  email: false
