language: ruby
sudo: false

rvm:
  - 2.1.5

before_install:
  - ls -l ~/.ssh
  - cat /etc/ssh_config || true
  - cat ~/.ssh/known_hosts || true
  - cat ~/.ssh/config || true

install:
  - true

script:
  - git clone git@github.com:travis-ci/travis-web.git
  - cat ~/.ssh/known_hosts
