language: ruby
sudo: false
install:
- true
script:
- true
notifications:
  irc:
    channels:
    - secure: "OwTCZyaqr4b2e18+FVQCIqp9dfZV+PEZG9vWTKwVLgfkxIy13iIn9u/QQezTH7W4DSDM2wf6slb8DLRb4W76yQ8f0LKPifMDFhf0OIT8WQQlX+9FIJ3xcu2A2udzfrpiQMjnFxP9rElQD3H8EQsM+vs5PVlog4LDGT0RWUYPB5o="
    nick:
      secure: "B5iTNZh+ARG5fda0kUZsLZrG4EMkAD7D3PCoaNpYWacqbJ2vYHZ8260/Apfpsu3JKrdQLu897RkR36NGcgO1+ypt5ugZMO/rDbTmjaUWP8Z3oGND76q4wwxzsEX8kAJwkBhx/Ktbo4oYvpEeGkA9xYtfEnm9JFP0xgxTdPytgS8="
    password:
      secure: "YVpqcmaxsCYc6iOv5h3TwQhCby3oRa10E0TLOSoWBFQxeIw4xqAj+yA0JTO7OD9PciUUY/rULuhK5AuSoye0lQALpWIvrxskmKVXeGtQcVbMYwY9UjZCj8Rak5M9ovstFCBltLwTBkJcSC2xQmbnbVEVOefm7l7+M9q8byJDaKg="
    nickserv_password:
      secure: "oKNhDjGFpAIuaxKnk+ALeVTo7o2A/OXPb/wTql5BlEJ03d9DoHqaRS4ijkkZ493DlDp/xUYtdc0DYhga+eF5dn+R3cxDIgJ55D1OGYXJFQpC1TOaNbTu0dWHdH53Y7HoWc2HjERg6RhIQVe3XQsa35KXy6lQO/qXPHOrZ4xWFLE="
