language: android

install:
  - PYTHON_VERSION=3.4.2
  - sudo python-build $PYTHON_VERSION /opt/python/python${PYTHON_VERSION}
  - sudo virtualenv --distribute --python=/opt/python/python${PYTHON_VERSION}/bin/python /home/travis/virtualenv
  - export PATH=/opt/python/python${PYTHON_VERSION}/bin:$PATH
  - which python
  - python --version

script:
  - ldd --version
  - java -XX:+PrintFlagsFinal -version | grep MaxHeapSize
  - for x in 5 10 100 1000 10000 100000 1000000 1280000; do echo $x; java -Xmx${x}g -XX:+PrintFlagsFinal -version 2>&1 | grep MaxHeapSize; done  
  - for x in 5 10 100 1000 10000 100000 1000000 1280000; do echo $x; export JAVA_OPTS="-Xmx${x}g"; java -XX:+PrintFlagsFinal -version 2>&1 | grep MaxHeapSize; done  
