language: python

sudo: false

addons:
  jwt:
    secure: "NvXCZP21Ftns970/7yLcwfUm2hTua73i3SVOR7Qx4ANSgqrGefM3CU3DPvnc963g/J38CUC51gkNgiQK0L5T8xOg0bAlg+Z3AQyeTprLyUfLK6hswXJ1iXRCknU9yf7wxdWZET/xET4WcSCRxtlQCAY9zUmdpFI3DzZhIG2xgNiRLj5xehEFDLMgL/UB0FHkaL2eS4tGty6u+OL+S2SbOOJdba4yJAAW/EGBM0RF3z7DPbm1GFEibOWLeKhO/LL5YrlBLNpJqmJzFyszTiKdOmUXhEz1bYFUL6AcjjRRYA2B6j5stVaduW2LHGwrrQ87ihULdhQxPIR8rNcEsIqUeTXM/mHAYoSV6Mknrcw3lCxNg2mJdvvP529hpcY222tIu2mospHAjcycLA8pUg2jahCEKMo2LPquaA/CIUJcIOE73mpabtnAHgU3tU5yR8HCHNL7Qk22afIjS9T8x8J3i7yNKYkyqKxA52+FilWea/+Mf5N0KptE+rDX4J967yKBsaex6hw75JaQvfauL+nd1MluOHt4hkx/t6eHl+Fgb0KtMOMrjFpHN5a2UUhg5gtCFIwWpK3BNeVojwsrYmJ1zTnhVKQztA7wguGDpFDziA7UQSf+a1/9NWZ3sG9WDW5FtkldQYbEADajm05afXW/1tVn2Sh4q/3RtGQ2uM2wiR4="

install:
  - true

script:
  - echo $SAUCE_ACCESS_KEY

notifications:
  email: false
  # slack:
  #   rooms:
  #     - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+miSjoFFbTn2v7hA="
  #   template:
  #      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time}) subject: %{commit_subject} message: %{commit_message}"