language: elixir

sudo: required

dist: trusty

elixir:
  - 1.2.4

otp_release:
  - 18.2

notifications:
  email: false

install:
  - true
script:
  - grep -C 3 'kiex' ~/build.sh
  - test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"
  - which kiex || true
