language: node_js

env:
  - LANG=ruby
  - LANG=php
  - LANG=python
  - LANG=perl
  - LANG=android
  - NUM=5
  - NUM=6
  - NUM=7
  - NUM=8
  - NUM=9

dist: trusty

node_js:
  - '0.10'

install: true

script:
  - docker run -i -t ubuntu /bin/date

