language: ruby

sudo: false

install:
  - true

script:
  - true

addons:
  firefox: '50.0b6'
  sauce_connect:
    user_name: "SUPER_DUPER_USER"
  jwt:
    secure: "bu9zz6G4Y35YJrRbCSbOA0+oojhsji+G4QiPMMqoW16PKvEioamuiJPQgflu1IVuRWiuB+MuOrrbeF4rfDNUvnTAIMfzSm42ZBurUUbqAxbYHhJfHavnyTjduHm3C0MnyRQP7YESDS4cSyWOFTMRp9OoLIHxHeDh7/Y7QZzKFmI="


notifications:
  email: false
#  webhooks: http://requestb.in/1365tca1
  # slack:
  #   rooms:
  #     - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+iSjoFFbTn2v7hA="
  #   template:
  #      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time})subject: %{commit_subject} message: %{commit_message}"
  #
  #env:
  #global:
  #  secure: Bw9BTZqRQ0hlJBInFMxMSQGdc8nMvFxfQQZNxbzrLCgNWZ8ow0sjG9oItOe/Otl7raapmZh+OZsqWAzqvfCfTyueqUaMfqhzB0hzjR8jxfpQP/99db2Ok/s2hOttcfyAKanlbQT7Cvy6SRv4VoFclAY8s6q8Migr8bCWkUjlQU=

