language: ruby

rvm:
  - 2.1.1
  
install:
  - true

script:
  - true

deploy:
  provider: s3
  on:
    tags: true
  access_key_id: foo
  secret_access_key: bar
  bucket: "my bucket"
  skip_cleanup: true
