language: ruby

sudo: true

install: skip

script: skip

jobs:
  include:
    - os: linux
      addons:
        firefox: latest
    - os: osx
      addons:
        firefox: latest
    - os: linux
      addons:
        firefox: latest-esr
    - os: osx
      addons:
        firefox: latest-esr
    - os: linux
      addons:
        firefox: latest-beta
    - os: osx
      addons:
        firefox: latest-beta
    - os: linux
      addons:
        firefox: latest-dev
    - os: osx
      addons:
        firefox: latest-dev
    - os: linux
      addons:
        firefox: latest-nightly
    - os: osx
      addons:
        firefox: latest-nightly
    - os: linux
      addons:
        firefox: latest-unsigned
    - os: osx
      addons:
        firefox: latest-unsigned
        
notifications:
  email: false
  # slack:
  #   rooms:
  #     - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+miSjoFFbTn2v7hA="
  #   template:
  #      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time}) subject: %{commit_subject} message: %{commit_message}"
