sudo: false

group: dev
dist: trusty

cache:
  bundler: true
  edge: true

services:
  - redis

script: true

hipchat: "a21b28b2863acbee3ccb17da36a173@Travis CI"
# hipchat: 
#   secure: QdY+hOyUbe3zU/BuEkgWghVniNmCF14ieEfFAKpnWVplkfGZ7o+SZTJ9erl+zPu6FRN160GLaKVJHwf1xDWaVDkF4RLN9NgEfY4ULXTBCCJ0CDxo1ikcRU5+6hgYDCr+yK3LmapIe1FhuEz1J8/m5no4NWwKF0V6J9oQ9U2mcQU=

# rvm: default

# git:
#   strategy: tarball

# env:
#   global:
#     - FOO=foo
#     - secure: "O5fJhyTAuCq8GYwFaXxZ+MFEb86ONsj9jWxz6/GQoCEIb3z6Ie6Kfzqb001JWsqOPQ8Wyn4EMtDlAY/7nzWW978fWOUEyag+zMDzQwCd1Mk2TA2PK7jNTDTw8OcTOHCkcMnQTJU3JebcLVpRIFnctx9jVJHbNCpe6kVsyl21Igg="
#   matrix:
#     - BAR=bar
#     - secure: "fIRtWVB5Xv5XwYepUCI56a5s4qt71QZEjxiRArzqJ3JsqBTZHI/EIxWXXojOYf6NLLA+yE+7wcUI68gqaLoHgTIuXdwn2mRFrCjlD0+aUpxmrruF7hIGy6ntE5KHxNY+VWKvxaS9qPALZidLlFj5lGKccHQngTckG1r0Gsj0kDA="

# script:
#   - env

# after_script:
#   - cat $HOME/.casher/fetch.log
#   - cat $HOME/.casher/fetch.err.log

# language: cpp
# matrix:
#    include:
#     - os: linux
#       compiler: gcc
#       env: JULIAVERSION="juliareleases"
#     - os: linux
#       compiler: gcc
#       env: JULIAVERSION="julianightlies"
#     - os: osx
#       compiler: gcc
#       env: JULIAVERSION="juliareleases"
#     - os: osx
#       compiler: gcc
#       env: JULIAVERSION="julianightlies"
