os:
  - linux
  - osx
language: nix
sudo: required
# workaround for a macOS specific issue with trusted users
before_install:
  - sudo mkdir -p /etc/nix
  - echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf
  - echo "substituters = https://cache.nixos.org https://d121dybo9yhl5h.cloudfront.net" | sudo tee -a /etc/nix.nix.conf
  - echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= d121dybo9yhl5h.cloudfront.net-1:IOpHdUBT2b3fIRb/TBm+V8Y8eEj52fStcllzD6TFYyU=" | sudo tee -a /etc/nix/nix.conf
  - sudo launchctl kickstart -k system/org.nixos.nix-daemon || true
install:
  - nix-env -iA cachix -f .
  - cachix use dapp
script:
  - |
    nix-env -iA nixpkgs.shellcheck
    grep -RHL --exclude-dir node_modules node src/*/libexec | xargs shellcheck --exclude=2001
  - |
    [[ -z "$TRAVIS_PULL_REQUEST_SLUG" || "$TRAVIS_PULL_REQUEST_SLUG" == "dapphub/dapptools" ]] && cachix push --watch-store dapp &
  - |
    [[ "$TRAVIS_OS_NAME" == "osx" ]] && PLATFORM=darwin || PLATFORM=linux

    nix-build -j auto release.nix -A dapphub.$PLATFORM.stable &&

    # this is here to let cachix finish pushing the last artifact before the script is killed
    sleep 10
after_success:
  - |
    if [[ -z "$TRAVIS_PULL_REQUEST_SLUG" || "$TRAVIS_PULL_REQUEST_SLUG" == "dapphub/dapptools" ]]; then
      COMMIT_HASH=$(echo $TRAVIS_COMMIT | cut -c 1-8)

      # Only run this on Linux to avoid announcing to the channel twice.
      # Using build stages is another option but is inefficient because it requires initialization of an additional VM.
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        nix run nixpkgs.httpie -c \
        http -f https://dapphub.chat/api/v1/chat.postMessage \
          X-Auth-Token:"$CHAT_AUTH_TOKEN" \
          X-User-Id:"$CHAT_USER_ID" \
          channel=#dev-announce \
          text=":construction_site: Nix build of dapptools [$COMMIT_HASH](https://github.com/dapphub/dapptools/commit/$COMMIT_HASH) (branch \`$TRAVIS_BRANCH\`) finished; binaries for GNU/Linux and Darwin uploaded to Cachix."
      fi
    fi
notifications:
  email: false
  #  webhooks: http://requestb.in/rin6s6ri
  #slack:
  #  rooms:
  #    - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+iSjoFFbTn2v7hA="
  #  template:
  #     - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time})subject: %{commit_subject} message: %{commit_message}"

  #env:
  #global:
  #  secure: Bw9BTZqRQ0hlJBInFMxMSQGdc8nMvFxfQQZNxbzrLCgNWZ8ow0sjG9oItOe/Otl7raapmZh+OZsqWAzqvfCfTyueqUaMfqhzB0hzjR8jxfpQP/99db2Ok/s2hOttcfyAKanlbQT7Cvy6SRv4VoFclAY8s6q8Migr8bCWkUjlQU=

