language: node_js

install: true

script:
  - true

deploy:
  - provider: opsworks
    access_key_id: AKIAI65HYMCAT2AOFKUX
    secret_access_key:
      secure: H8T711FSQHYvZtQfdwQqdlP2wgHbrTAS3JO3ZTcLCNfjrOFW1m9WFc7L8Q9Lpuo9sclRc98IuIXGlBVXuG5CQa+MdmGN7zz+Jyr+OmWtCJJRtGvqvkVVEPLNeW1h3EzsSn77L2AiEEfg2QfRHPDiZSRK4kamvADUWrHI6qnFvSE=
    app-id: ea4b220f-4adb-4a89-908d-cff653e57b7e
    on: foobar
