language: ruby

sudo: false

install: true

script: true

addons:
  sauce_connect:
    username: "jdanekrh"
    access_key:
      secure: "dRLcC1JYrl0tnwIKBqPixuR9pbpGdJJB7oDzj1dr56FfXuu8+JTyy+Tvsz7OBE7EDreuxOPV5Yd5v/+DF+iw9+1QHTjenfFD0Qj79cm+8tyjESBeKuD11SCEyKMksySbF3RShOdsof3W08uPg/Jlowxel1VtUWRVY54Ht8svLg/aigVtM1Px1XME1kIXav1n6nQvUsdA8nnCfqagh6ctGQcmjBVJqskYPl8jyMuovFKnnZ8hCpq5vMMxIhsahdEzwvU1RI20Sci9Fc7B2ux6jFX0JqYR7t/HrskMVNS4lBcH/JHVb+7L96W1bUXgTb1xrZyKdgyE+PM1Lcx7jxV23wU5x4K7Sl6olIwE9qXJDXW3e4tsxjeR+PFU/duiq85ezgTimsZGNISGSaNenYI+PMTeLjfDdgw19eT8X8j26pAnQ5K/pydsNahlwpXRoF2iz4x5WOgNGjHnhuDOUR376S0DbV1GGnq7d5Yzu2JH5VjnaXSbY8kD42i1Uxfiod/4YtSqmDJGdH4Nha0DLVE5gYgXhRs3qPndf6Prw6lKTZ/Q0Awj19HVXEX4M1Ht4kfLojUAPCpclcK4fIWW73mzfyfNBQutDaw+H4NHE4AzrOHNdVOGH94q6RYa8rmKMKtBksF7kMfbBg2IC/jZb2vLhb/4ys48Ceno8Uxd8ETDMX4="
    no_ssl_bump_domains: "127.0.0.1,localhost"

dist: precise

sudo: false

# addons:
#   firefox: latest

# matrix:
#   include:
#     - sudo: required
#       dist: precise
#       ghc: 8.2.1
#       env: DIST=precise STACK=GCE
#     - sudo: false
#       dist: trusty
#       ghc: 8.2.1
#       env: DIST=trusty STACK=EC2
#     - sudo: required
#       dist: trusty
#       ghc: 8.2.1
#       env: DIST=trusty STACK=GCE
#     - os: osx
#       osx_image: xcode8.3

  #  webhooks: http://requestb.in/rin6s6ri
  #slack:
  #  rooms:
  #    - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+iSjoFFbTn2v7hA="
  #  template:
  #     - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time})subject: %{commit_subject} message: %{commit_message}"

  #env:
  #global:
  #  secure: Bw9BTZqRQ0hlJBInFMxMSQGdc8nMvFxfQQZNxbzrLCgNWZ8ow0sjG9oItOe/Otl7raapmZh+OZsqWAzqvfCfTyueqUaMfqhzB0hzjR8jxfpQP/99db2Ok/s2hOttcfyAKanlbQT7Cvy6SRv4VoFclAY8s6q8Migr8bCWkUjlQU=

notifications:
  email: false
