language: ruby

sudo: false

install: true

script: true

deploy:
  provider: boxfuse
  edge:
    source: 'axelfontaine/dpl'
    branch: 'master'
  access_key_id: foo
  secret_access_key: bar
  bucket: baz
  on:
    all_branches: true

