language: ruby

sudo: false

cache:
  bundler: true
  directories:
    - vendor/bundle

env:
  - secure: "gwGZG/kNYovmxcJN5selYqwi09+byePzmiuTjcK3UoD1VMwco5or5OhnGHuZU7kRlrwfHI6DOp3r6llTChg9WIens3Kgz4ISOKa/0FyXOkj96H3uJInN2gnYxJuIXDZoyEChRJPJlNhJ0DwEPWhaAygI3W5YO3Jsge1qaFrEFfY="

script:
  - true

notifications:
  email: false
  slack:
    rooms:
      - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+miSjoFFbTn2v7hA="
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time})"
