language: php

sudo: false

install: true

script:
  - true

notifications:
  email: false
  irc:
    channels:
      - secure: "G+WNYQPSw9hhNKGpyqAUgKIn6tytp6CZ97o9fTqqatA1gBUyn/sCvSJ9nggsCx+ywtuaX97Y/W8dyh63PD5MuwpjBOccW3umUDJDleSJNtK3rckeu/41CYfWpF3quaqGpEhZRmGLiW78b+dCR3wbZNIqkJgNEJYpDhVmyWR2IdA="
    nick: guest38470138471304

