language: node_js

sudo: false

node_js:
  - '4.2'

install: true

script:
  - gcc -v
  - g++ -v

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
