language: node_js

env:
  - LANG=ruby
  - LANG=php
  - LANG=python
  - LANG=perl
  - LANG=erlang
  - LANG=jvm

dist: trusty

node_js:
  - '0.10'

install: true

script:
  - docker run -i -t -u travis quay.io/travisci/travis-$LANG /bin/date

