language: ruby


install: true

script:
  - true
  - false

env:
  matrix:
    - TARGET='-Ptest'
    - TARGET='-Prake -Dtask=test:extended'
    - TARGET='-Prake -Dtask=spec:ci_interpreted_travis'
    - TARGET='-Prake -Dtask=spec:ci_interpreted_ir_travis'
    - TARGET='-Prake -Dtask=spec:ir'
    - TARGET='-Ptruffle'

matrix:
  allow_failures:
    - env: TARGET='-Prake -Dtask=spec:ci_interpreted_ir_travis'
    - env: TARGET='-Prake -Dtask=spec:ci_interpreted_travis'
