language: php

sudo: false

install: true

script:
  - true

notifications:
  email: false
  irc:
    channels:
      - 'chat.freenode.org#travisstaging'
    nick:
      secure: "VMlbfgKbNyEeK6vQPn34k0pDW0X3IGfOscYxukx49sb2x1dT9GYcfWBtyvtxIMIYPNZ5goYqFm3WrI/ZjmGSdAMKJDcxI2NIW1Ggi6EE4T4eabhRsJT5Ra498kXSTvysz286QFg+JZDyNbIXE9Ya5p1X7lBAwXTerSEdQaiaOn8="

