language: ruby

sudo: false

cache:
  bundler: true
  edge: true

install: true

script:
  - true

notifications:
  irc:
    - 'irc.efnet.org#nonexistentchannel'
  on_success: always
  on_failure: always
