language: ruby

sudo: false

install:
  - true

script:
  - env | grep -c SAUCE || true

addons:
  jwt:
    secure: "M2rgVW/bBf+YJPXMw2rupSCl/6k+5zCAklid3KPPPE2LxjmTPV9BlJLEK09JvdnSvk6wcJrOxL/o9OEX3ETbHtTSLIDzqP457Etrl5ZI6ivaQE/k85iH9Mhkp2mmJ9qXkg7BvTsqkj39JZwt2LpmKpaP7S2T83fsBRMuPVaBtHxKNHu1SJa32WvwNqXoQpcBSjyfSOfAmLw2MXvgNhI2i3uUFZcaPmDv0S7trjNFKYRzw95qRGWDl/EK8U8tIaGT+R26xuDfvNaOzEpRiaI+GnJLt2oOgqriZCvpFoCeXXN60DW5/4xv9lVYO1VgswmT6cfimfWMu5hHFcRivcmZ1lusoP5pKLDgXA97IUdVUd4alv3oP1DBlWvGtGc46ejMhBjxnDQE67AJ/yMbJIT3wav0JNQMxvx3UsmZjbXcg4B13PW1pXnKkxMc2JI8QfM+WEJt+3BqAhT/K4Ey4Z50S33L8+5zl5klmx+cQA+xzvG9sNn7p0ksD6CjlgOrZSgsEZV7pzyD+WmOZV5mRzwa77swi6vRpMk+lqD2EQ9Faasq4Gq6zldHtNJzwb9IpesnCbFVGSW0lzJUausfvQlmySabscvKOA3FreCe4042qD8Db6FKsBdXQoclrjYdyVG95nIZnyK/Cx6BQv4ifXZc0p29OTP9ciSHgGYXgghX7kU="

notifications:
  email: false
  slack:
    rooms:
      - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+miSjoFFbTn2v7hA="
    template:
       - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time}) subject: %{commit_subject} message: %{commit_message}"
