language: ruby

sudo: false

cache:
  bundler: true
  edge: true

install: true

script:
  - true

notifications:
  webhooks:
    - https://nonexistentdomainandsuch.com/blah
  on_success: always
  on_failure: always
