language: ruby

sudo: false

install: true

script: true

addons:
  browserstack:
    username: "jiridanek1"
    access_key:
      secure: "yB5uMh21ZW7MULaKmxplao3DYcanUPV3gyWmXue8A9ILTmGzgbJgm+HNLY8SL9lRT/PHAxZ741n6gqCAbanTpe74GicvebeMQjlJ4VWo5762pCaB5f/neM8g2sPZLIRNn0YxyuEWe7kkmP0AZ7tjHKqPc34avhobaURNDoVC8/2uaUFaqqs6T9MX9j7EKObT0BsFDygsSHRlzWcN5pmvVg25J20+F8aAwOx0mKWXn/c0wN9NSYGrB3JnuzBQFfs6M/DB36+kxrSo4xBrZ//HTqPWYTpsvq2nIJjzUY0wHowuGNRga90mFvlRFuRObn9pH8gSYWwQ4gTYayZKYoQdVtmrQpvVvrBE0YXE4ZBzFRbjw3INIrX7CTcTc9VVW1C4aMR2e8UKkh+vFSdcw9ibc4+hVoiEE+e23wgp/HjnNEtHrT1khDWJkmKmiF41IAqfFq4Zb7wPdR604Nb8XSUnhyaqt969vhmCzXdqtNcwpB/dN7EWBENzMh9Fv0NGJDX5aaQLUfVNQ5I5jwt+4TjPKGkiOiHIDH+/h8o7qvvgKe07Q0kXhpRkz4+abKzW3fuizpwGhiQlExsnM4Rg8k/5mIKSz4m0ydIL3CrNmsHg3Noc1dUMzhbAS5sQOSdWfi9LYmWRjbyoEu5A3ECbp8MnT4q9wRwD7jX2zMWKoEnce40="

dist: precise

sudo: false

# addons:
#   firefox: latest

# matrix:
#   include:
#     - sudo: required
#       dist: precise
#       ghc: 8.2.1
#       env: DIST=precise STACK=GCE
#     - sudo: false
#       dist: trusty
#       ghc: 8.2.1
#       env: DIST=trusty STACK=EC2
#     - sudo: required
#       dist: trusty
#       ghc: 8.2.1
#       env: DIST=trusty STACK=GCE
#     - os: osx
#       osx_image: xcode8.3

  #  webhooks: http://requestb.in/rin6s6ri
  #slack:
  #  rooms:
  #    - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+iSjoFFbTn2v7hA="
  #  template:
  #     - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time})subject: %{commit_subject} message: %{commit_message}"

  #env:
  #global:
  #  secure: Bw9BTZqRQ0hlJBInFMxMSQGdc8nMvFxfQQZNxbzrLCgNWZ8ow0sjG9oItOe/Otl7raapmZh+OZsqWAzqvfCfTyueqUaMfqhzB0hzjR8jxfpQP/99db2Ok/s2hOttcfyAKanlbQT7Cvy6SRv4VoFclAY8s6q8Migr8bCWkUjlQU=

notifications:
  email: false
