language: c

cache:
  directories:
    - ~/.ccache
  
before_install:
  - sudo apt-get install ccache

script:
  - mkdir ~/.ccache
  - echo "foo" > ~/.ccache/foo
  - grep add ~/build.sh
  - echo $CCACHE_DISABLE
