language: ruby

sudo: false

install:
  - wget -O installer.sh http://www.cs.utah.edu/plt/snapshots/current/installers/min-racket-current-x86_64-linux-precise.sh
  - curl -vvvv -L -o installer.sh http://www.cs.utah.edu/plt/snapshots/current/installers/min-racket-current-x86_64-linux-precise.sh
  - sh installer.sh --in-place --dest ~/racket/

script:
  - cat /proc/sys/net/ipv4/tcp_ecn
  
