language: ruby

sudo: false

install: true

script: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - ccache
    - debhelper
    - devscripts
    - doxygen
    - dput
    - espeak
    - g++-4.8
    - gcc-4.8
    - graphviz
    - libc6-i386
    - libespeak-dev
    - libgstreamer-plugins-base1.0-dev
    - libgstreamer1.0-0:amd64
    - libgstreamer1.0-dev
    - libopenscenegraph-dev
    - libsdl1.2-dev
    - libudev-dev
    - texlive-font-utils
    - wget

notifications:
  email: false
  slack:
    rooms:
      - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+miSjoFFbTn2v7hA="
    template:
       - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time}) subject: %{commit_subject} message: %{commit_message}"