language: objective-c
 
cache:
  bundler: false
  directories:
    - node_modules
    - bower_components
 
before_install:
  - export PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH
 
install:
  - npm install
  - bower install
 
script:
  - true
