language: php

php:
  - 5.2
  - 5.3

install:
  - true
  
script:
  - php -r 'var_dump(file_get_contents("https://google.com"));'

# notifications:
#   email:
#     recipients:
#       - asari.ruby@gmail.com
#     on_success: always
#     on_failure: always
#   hipchat:
#     rooms:
#       secure: "E5FYOudzhEqM8UKJilfIka4UHJu+WGfr0t6BCYoLMsXlMNh099eunwbmcz978j9+X5VVvi7WEToSUs47c7RnjODsDYKdYfrGTcuiCs1y+vJnbdUG4Pi2sfrCTTHcmkm+wv9fL7z3OIA8eMIO8utyMl0ewLGyscLaZJa9/hdUT6E="
#     on_success: always
#     on_failure: always

addons:
  hosts:
    - example.com
    - foobar.com
