language: ruby

sudo: required

dist: precise

cache:
  bundler: true
  edge: true

rvm: default

notifications:
  email: false

script:
  - sleep 300
  - sleep 300
  - sleep 300
  - sleep 300
  - sleep 300
  - sleep 300
