language: ruby

sudo: false

cache:
  bundler: true
  edge: true

rvm: default

notifications:
  email: false

script:
  - mkdir log
  - cat ~/build.sh

addons:
  artifacts:
    paths:
    - log/
    branch:
      - 'master'
