language: ruby

install: "sudo pip install -r requirements.txt --use-mirrors"

group: dev

addons:
  postgresql: "${PG_VERSION}"

before_script:
  - psql -c 'create database travis_postgis;' -U postgres
  - psql -f init_postgis.sql -U postgres -d travis_postgis
  - psql -f test_data.sql -U postgres -d travis_postgis

script: nosetests --verbose

env:
  - PG_VERSION=9.4
  - PG_VERSION=9.3
