language: python

python: '3.5'

matrix:
  include:
    - sudo: required
      dist: trusty
      env: RELEASE=trusty
      addons:
        apt:
          sources:
            - sourceline: "deb http://packages.elastic.co/elasticsearch/2.2/debian stable main"
              key_url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
          packages:
            - elasticsearch
    - sudo: required
      dist: precise
      env: RELEASE=precise
      addons:
        apt:
          sources:
            - sourceline: "deb http://packages.elastic.co/elasticsearch/2.2/debian stable main"
              key_url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
          packages:
            - elasticsearch
    - sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb http://packages.elastic.co/elasticsearch/2.2/debian stable main"
              key_url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
          packages:
            - elasticsearch


install:
  - true

script:
  - true

notifications:
  email: false

# notifications:
#   email: false
#   slack:
#     rooms:
#       - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+miSjoFFbTn2v7hA="
#     template:
#       - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time})"
