language: ruby

dist: trusty

install:
  - true

services:
  - cassandra
  
script:
  - /usr/local/cassandra/bin/nodetool version
  - ps -ef
  - ruby -r socket -e 'puts TCPSocket.new("localhost", 9042)'
