language: ruby
cache: bundler
sudo: false

env:
  matrix:
    # The first one is intentionally empty in order to run without any extra env vars
    -
matrix:
  include:
    - env: FOO=BAR

install:
  - true

script:
  - true

notifications:
  email: false
