language: ruby

cache: bundler

matrix:
  include:
    - sudo: required
      dist: trusty
      group: edge
      rvm: '2.3.0'
    - sudo: false
    rvm: '2.3.0'

notifications:
  email: false

script: true
