language: ruby
dist: trusty
sudo: false

install: skip

addons:
  ssh_known_hosts:
    host: '199.182.121.223'
    type: ssh-rsa
    key: AAAAB3NzaC1yc2EAAAADAQABAAABAQDHRC2t75Wuki5djGSaxK/RfISQKRzDk1Ir2gaUppd+E4X9S/getLt7NoIdRcO9pdUYyK056g8StR/Dj2lMB4a5Xsdabj+zxOctBtFIq16p27hyy5A4EgY/a4fOy0CPaeyQpDc6Kv23KQAwVUDSphVBx6gOqmWJ+Kvf96fmeH51ODt0M0YUbHdfsTKXcZJgB/JlEd//rLN4dIzqAWpQgmNZPeIthlVOLWkj2sffuy2A1t+viJ6JHKz/wnJEv3OiVMIZ3obWdI
Yjuj1CaVChdwrSPGBdhdhmGsXLfG0KmvJeSqd7WhFsnskN8jxl6XrQG2Vxk5pZM6GZZ+a6ow0umhGr

script:
  - cat /etc/hosts

matrix:
  include:
    # - sudo: required
    #   dist: precise
    #   env: DIST=precise STACK=GCE
    # - sudo: false
    #   dist: trusty
    #   env: DIST=trusty STACK=EC2
    # - sudo: required
    #   dist: trusty
    #   env: DIST=trusty STACK=GCE
    # - sudo: required
    #   dist: false
    #   env: DIST=trusty STACK=EC2
    # - os: osx
    #   osx_image: xcode9.2
    # - os: osx
    #   osx_image: xcode9.1
    # - os: osx
    #   osx_image: xcode9
    # - os: osx
    #   osx_image: xcode8.3
    # - os: osx
    #   osx_image: xcode8
    # - os: osx
    #   osx_image: xcode7.3
    # - os: osx
    #   osx_image: xcode6.4

# deploy:
#   edge: true
#   provider: script
#   script: echo $(travis_internal_ruby)
#   on:
#     all_branches: true
# deploy:
#  provider: releases
#  api_key:
#    secure: "JFN13iCV/XC1Jn9nwZ0/fjc18OB+JobYQcZQWFNRP2geAfrfvTb1FcGumMXsa/sQjyuTT7yCjPZtToSk6kqXAIlVq08OXLL5nXz0fiIp/dh6aRrOYn6Ddg8P9Vi05a+VFgWnd280VgeFIP+X8d6TuXKiyPLXVNsr7oCdU67Swj4="
#  file: "Rakefile"
#  skip_cleanup: true
#  # on:
#  #   all_branches: true

notifications:
  email: false
  #  webhooks: http://requestb.in/rin6s6ri
  #slack:
  #  rooms:
  #    - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+iSjoFFbTn2v7hA="
  #  template:
  #     - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time})subject: %{commit_subject} message: %{commit_message}"

  #env:
  #global:
  #  secure: Bw9BTZqRQ0hlJBInFMxMSQGdc8nMvFxfQQZNxbzrLCgNWZ8ow0sjG9oItOe/Otl7raapmZh+OZsqWAzqvfCfTyueqUaMfqhzB0hzjR8jxfpQP/99db2Ok/s2hOttcfyAKanlbQT7Cvy6SRv4VoFclAY8s6q8Migr8bCWkUjlQU=

