# sudo: false

language: objective-c

cache: 
  bundler: true
  edge: true

services:
  - redis

script: true
after_script: 
  - cat $HOME/.casher/fetch.log 
  - cat $HOME/.casher/fetch.err.log

# language: cpp
# matrix:
#    include:
#     - os: linux
#       compiler: gcc
#       env: JULIAVERSION="juliareleases"
#     - os: linux
#       compiler: gcc
#       env: JULIAVERSION="julianightlies"
#     - os: osx
#       compiler: gcc
#       env: JULIAVERSION="juliareleases"
#     - os: osx
#       compiler: gcc
#       env: JULIAVERSION="julianightlies"
#         
