language: ruby

sudo: false

addons:
  postgresql: '9.5'

services:
  - postgresql

rvm:
  - 2.1.5

before_install:
  - psql -c 'create database travis_ci_test;' -U postgres

install:
  - true

script:
  - postgres --version
  - env COLUMNS=132 dpkg -l | grep postgres
  - dpkg-query -L postgresql-9.5
  - dpkg-query -L postgresql-client-9.5
  - dpkg-query -L postgresql-contrib-9.5
  - lsof -P | grep 543
