language: ruby

sudo: false

addons:
  postgresql: '9.3'

rvm:
  - 2.1.5

install:
  - true

script:
  - postgres --version
  - env COLUMNS=132 dpkg -l | grep postgres
  - dpkg-query -L postgresql-9.3
  - dpkg-query -L postgresql-client-9.3
  - dpkg-query -L postgresql-contrib-9.3
