language: python

sudo: false

addons:
  apt:
    packages:
    - python-argparse
    - python-lxml
    - python-mysqldb
    - python-redis
    - python-tz
    - python-zmq
install:
  - true
script:
  - true
  
