language: ruby

rvm:
  - 1.9.3
  - 2.0.0

os:
  - linux
  - osx

script:
  - true

deploy:
  provider: rubygems
  api_key:
    secure: foobar
  gem: beeeeeeeeeeeeeeeeeeeeeeeeeeeeeer
  on:
    repo: travis-ci/travis.rb
    ruby: 2.0.0
    condition: "$(uname) = Darwin"
