language: ruby

rvm: default

sudo: required
dist: trusty

cache:
  bundler: true
  edge: true

script:
  - cat ~/build.sh

after_script:
  - cat ~/.casher/md5sums_before
  - cat ~/.casher/md5sums_after
  - cat ~/.casher/checksum_diff

notifications:
  email: false
