language: ruby

rvm: default

matrix:
  include:
    - sudo: required
      dist: trusty
    - sudo: required
      dist: precise
    - sudo: false

install:
  - true

script:
  - cat /etc/apt/sources.list

notifications:
  email: false
