language: ruby
cache: bundler
sudo: false

env:
  matrix:
    # The first one is intentionally empty in order to run without any extra env vars
    -

rvm:
  - 2.3.0

matrix:
  include:
    - sudo: required

install:
  - true

script:
  - true

notifications:
  email: false
