language: ruby

sudo: true

env:
  global:
    - secure: "A8i4cnQo3v32gKBIVkUccsJXbmG2bvBiH4e36uQWVaQvQDzufuoDll7T5MMjrsm4uc7Ki0JR3gMLtM/GsWeO3WeTuwxol53nar2+I1hbFvIflGiYBETCNoZqKetxLu2WcAeoyUK9oHCeDq/Z1w5zQcZH+vzs4k9Frplrd3itvSY="

install: skip

script: skip

notifications:
  email: false
  slack:
    on_start: always
    rooms:
      - secure: "meu5RUiQjes/VOgw6y3Udto8cDUWWd+l/BJZSbEcqhjbwSiphC+QbOmM9rgcXlDujC52GNx/KIkqjd8Gsuwc7xP3cjaoow38pyiA2Zs3ttj/pXT1kg5qZbT1R8x9aICp3dxZZySATWPknMV5UsyTYb5j6qwU6reSnJNuzd8nJ48="
    template:
       - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time}) subject: %{commit_subject} message: %{commit_message}"
