language: ruby

sudo: false

dist: trusty

install:
  - true

script:
  - true

addons:
  sauce_connect:
    username:
      secure: "FcpwNWPOSaASe7iBd0XRbY8ZhZfN9ox0wUZMHxrlvMHfwom+cqVKiygtXShQCNlq9+9vSXQett76xqaQwbTaq/Pnn/Y4FmecaLw+RcbfVSjLjFzw6l+UqsKGZLismaNjfAb/YDrIDVjeG3Z+fMdRUOzihHR2P1qgLNwEtM3yYro="
    access_key:
      secure: "GsjREudfNLfvZAgcVzyM/5GVE5KdyDW31lgLijma8rDnvxSQB8/zfGYooyJyTiuQB75ubAZD/Qih4lrLmCsSRfAv06myfzAl4c7WhlzuraZtyD8N/aDkjFGzNtiiAtEb/iWhzkV0hTMT4PO71uJc6kEtqMp7sei7oom2gk8yRuI="

notifications:
  email: false
  #  webhooks: http://requestb.in/rin6s6ri
  #slack:
  #  rooms:
  #    - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+iSjoFFbTn2v7hA="
  #  template:
  #     - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time})subject: %{commit_subject} message: %{commit_message}"

  #env:
  #global:
  #  secure: Bw9BTZqRQ0hlJBInFMxMSQGdc8nMvFxfQQZNxbzrLCgNWZ8ow0sjG9oItOe/Otl7raapmZh+OZsqWAzqvfCfTyueqUaMfqhzB0hzjR8jxfpQP/99db2Ok/s2hOttcfyAKanlbQT7Cvy6SRv4VoFclAY8s6q8Migr8bCWkUjlQU=

