language: ruby
cache: bundler
sudo: false

env:
  matrix:
    # The first one is intentionally empty in order to run without any extra env vars
    - FOO=BAR

rvm:
  - 2.3.0

matrix:
  include:
    - rvm: 2.3.0
      gemfile: gemfiles/Gemfile.sinatra-edge

install:
  - true

script:
  - true

notifications:
  email: false
