language: ruby

sudo: false

addons:
  posrgresql: '9.4'

install:
  - true

script:
  - psql "postgresql://localhost:5432/postgres?sslmode=disable" -c "show server_version"
  - psql "postgresql://localhost:5432/postgres?sslmode=require" -c "show server_version"

notifications:
  email: false
  slack:
    rooms:
      - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+miSjoFFbTn2v7hA="
    template:
       - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time}) subject: %{commit_subject} message: %{commit_message}"
