language: node_js

sudo: false

node_js:
  - '0.12'

install: true

script: true

deploy:
  provider: boxfuse
  edge:
    branch: '+refs/pull/319/merge:'
  access_key_id: foo
  secret_access_key: bar
  bucket: baz
  on:
    all_branches: true

