language: python

sudo: false

env:
  - FOO=bar BAR=baz

install:
  - true
  
script:
  - true

deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"
  on:
    condition:
      - 'FOO = bar'
      - 'BAR = baz'
