language: ruby

sudo: false

rvm:
  - '2.1.5'

install:
  - true

script:
  - cat ~/.ssh/config

matrix:
  include:
#    - php: 5.4
#      env: DB=mysql
#    - php: 5.4
#      env: DB=pgsql
#    - php: 5.4
#      env: DB=oracle
