language: python

sudo: required

python:
  - pypy-5.3.1
  - pypy3.3-5.2-alpha1
  - pypy-5.3.5 # nonexistent

matrix:
  allow_failures:
    - pypy-5.3.5

install:
  - true

script:
  - true

notifications:
  email: false
  # slack:
  #   rooms:
  #     - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+miSjoFFbTn2v7hA="
  #   template:
  #      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time}) subject: %{commit_subject} message: %{commit_message}"