sudo: false

cache: 
  bundler: true
  edge: true

services:
  - redis

env:
  global:
    - FOO=foo
    - secure: "gXGxIO//Ed07PIuiWafwlaM1D7B4fcUZMSpIDVqDvZWtErND636ONu2IVurx2ikp9Pqnsc7flsVz4Ym5tLrwELhvaybPYovdKlyAOXKjD0AKCrodpKJ2+lYa8cR2/LrrXngBVYLK55zSdbyEX+hUfBGtvUyaz9FRa10OFku70u4="
  matrix:
    - BAR=bar
    - secure: "IshpiVH3tde4rqfpQA4zO0xe6RMekjabSJYcT8KxD5+kVvL7WMwpKRwoNf7akeAE7o572qkbcCkMFLaQKQm9Ij+Y02sh2gyuuepLfhEO4APN7426tcejd5RxFrma4VP0cBNtiYkVYe9vZZWkHHHkztrpp2LB0n5eg54u1vvib1Q="

script:
  - 'echo "global_env: FOO=$FOO"'
  - 'echo "global_env: SECURE_FOO=$SECURE_FOO"'
  - 'echo "env: BAR=$BAR"'
  - 'echo "env: SECURE_BAR=$SECURE_BAR"'
  - 'echo "settings: BAZ=$BAZ"'
  - 'echo "settings: SECURE_BAZ=$SECURE_BAZ"'
  
after_script: 
  - cat $HOME/.casher/fetch.log 
  - cat $HOME/.casher/fetch.err.log

# language: cpp
# matrix:
#    include:
#     - os: linux
#       compiler: gcc
#       env: JULIAVERSION="juliareleases"
#     - os: linux
#       compiler: gcc
#       env: JULIAVERSION="julianightlies"
#     - os: osx
#       compiler: gcc
#       env: JULIAVERSION="juliareleases"
#     - os: osx
#       compiler: gcc
#       env: JULIAVERSION="julianightlies"
