language: ruby

sudo: false

install:
  - true

script:
  - env | grep -c SAUCE || true

addons:
  jwt:
    secure: "CFYF8hEfE7PBDCrhvdbMdxn61L2gT3xh/KzqT+ZdmTsBiouIbA1H6nlmSLVBSQTWHf/b+WKVh6tnYpTvt0XWX3DrjGZVOJdAOcuCCJH6MxiVlVE17b7ahoTsnIubbAYz0Y1Vh3NgAyeejBM66FJXqjzUVXD40Ulr9dMaFZF1mBKPS3BvzN+pwn0jI3Yjfkfh/t9HdXijehpXWxHMsSBEnUtd/qdY53thJoiDcb69nXcqd5392DmzUh7AT4eqTloIsl+GQ+0s9LqHR+5a6ypacZ9RAs8GB8tHoxSObEsT7NcpDJiiwYuPl/+51FRC91g8WbVF5kzCNHeyXJuMFBTaAyAF9DmY5RMg3T+JgWOIIkj1RfP87LFd33s1Uawj+8iUtVWx1h8qfp5RlBcqq3JCK/S1vurj3iggtarwY6xIXy8rMIQNrB361Ef5fE9RXaFxaTIflsOWFdn8ZZK7iOLY7L6VBwYgC4VW+nel/sfHZvo8s1FAkQR5eE+iW+t+XBQ7W8zrPEYy0Bn47dIeoKgOm4/pZJmNgHdK0amhpQqfMYrv7bKfBd1qWFWjv/gdtUy7HRm6QWH9O8qTN4isIFYa61t2HSWPsatfM24snbUNiEFAbHofPTsyMrqpMrvGnsX/pY7GZlzSoQgZ913xpfQaLGaYWBHg47xmPYDfYM2I6lU="

notifications:
  email: false
  slack:
    rooms:
      - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+miSjoFFbTn2v7hA="
    template:
       - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time}) subject: %{commit_subject} message: %{commit_message}"
