language: node_js

node_js: 5

sudo: false

install:
  - curl -o ~/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh
  - source ~/.nvm/nvm.sh



script: nvm --version

notifications:
  email: false
