language: erlang

sudo: false

cache:
  branch: 'ha-feature-exit-status'
  directories:
    - foo

script:
  - cat $CASHER_DIR/fetch.log
  - cat $CASHER_DIR/fetch.err.log
  - echo $CACHE_FETCH_EXIT_STATUS
