language: php

sudo: false

install:
  - true

script:
  - ulimit -n
  - ulimit -n 50000
  - ulimit -n

notifications:
  email: false
  # slack:
  #   rooms:
  #     - secure: "lJvygEEwbvbTua6vhOQCgg/voA7iH9sgm6yj9pC9fnYBf++8DWbyyM3sUB3ZIBaeqUlwiEXmn5HjgQlzB1+JTHPtOJtd05m72kOOSEIcXqcLK3Of51E4fEzjrAZ4x/nJQeIIrUzpnlVrSpgFkCP1qNWq1AV+miSjoFFbTn2v7hA="
