language: ruby

addons:
  mariadb: "5.5"

install: true

script:
  - mysql -u root -e "SELECT VERSION(); SELECT NOW()"
  - mysql -u root -e "CREATE USER 'travis'@'%' IDENTIFIED BY '';          GRANT ALL PRIVILEGES ON *.* TO 'travis'@'%'; CREATE USER 'travis'@'localhost' IDENTIFIED BY '';  GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost'; CREATE USER 'travis'@'127.0.0.1' IDENTIFIED BY '';  GRANT ALL PRIVILEGES ON *.* TO 'travis'@'127.0.0.1';"
