language: python

python:
  - 3.4.3
  - nightly
  
matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - RELEASE=trusty
    - sudo: false
      env:
        - RELEASE=precise

install: true

script: true
